services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - .:/app:cached
      - /app/node_modules
    env_file:
      - .env
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5430:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s 

        
volumes:
  postgres-data:
    driver: local
