services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5430:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5430/postgres?schema=public
    depends_on:
      - db
volumes:
  postgres-data:
