services:
  web:
    build: .
    ports:
      - 3000:3000
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5430:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: