services:
  db:
    container_name: pgdb
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5430:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  postgres-data:
