services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      -  :5432   #port problem can be solve using this one
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  postgres-data:
